### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by le4ker**
Fixed typos :smile:

### CODE REVIEW

**Comment by mpgn** [comment]
Hello,
I will look into it ;)

**Comment by mpgn** [comment]
Nice update. I think you should also change this line : 
`If P'i ⊕ 0000000Y == abcdefg5 then:` by `If Pi ⊕ 0000000Y == abcdefg5 then:` and the other one with the second byte.

Can you refactor all the commit in one commit ? thanks

**Comment by le4ker** [comment]
Nice update. I think you should also change this line :
> If P'i ⊕ 0000000Y == abcdefg5 then: by If Pi ⊕ 0000000Y == abcdefg5 then: and the other one with the second byte.

I updated the examples as well :smile:

> Can you refactor all the commit in one commit ? thanks

I think you can select to squash the commits of the PR when you merge it, don't you?

**Comment by mpgn** [comment]
Nice, thx @PanosSakkos didn't know about this feature ;)

**Pull request merged**
